### ISSUE TITLE
Missing jdk.unsupported.desktop module from JREs (OpenJFX)

### ISSUE THREAD

**Issue by Jugen** [AdoptOpenJDK/openjdk-support#12]
Both the OpenJ9 and the Hotspot 11.0.3_7 **JRE** for 64bit Windows are missing the `jdk.unsupported.desktop` module.

This module is _required by_ the JavaFX 12 `javafx.swing` module.
For more information see [JDK-8202175](https://bugs.openjdk.java.net/browse/JDK-8202175) and this [openjdk-jfx issue](https://github.com/javafxports/openjdk-jfx/issues/458).

**Comment by persal** [comment]
I don't understand how this can be a low priority item, javaFX not working in JRE  greater than 11?

**Comment by aahlenst** [comment]
@persal That‘s easy to explain. With the introduction of JPMS, the JRE target was deprecated. Instead, people should use jlink. We‘re keeping the JRE around as one of the last vendors. But it starts to fall apart. Adding things to the JRE like jdk.unsupported.desktop would be like swimming against the current.

This does not necessarily mean that keeping the JRE alive or fixing that problem would not have been a good idea.

So, alternatives: Use jlink, you can even try our very own https://github.com/AdoptOpenJDK/jlink.online.

Some people here are thinking about whether we could provide a JRE replacement built with jlink. But at the moment, those are only pipe dreams.

**Comment by persal** [comment]
@aahlenst thanks for commenting on this. In a far future we might look at using jlink to build our own image. Since you also consider it being far away for adoptopenjdk to provide this, I assume it is not very straight forward putting together such a dist even with the adoptopenjdk's knowledbase.

Are we allowed, by license, to strip down the adoptopenjdk JDK dist by removing some files and directories and redistribute it to our customers?
For example removing:
```
jmods/
man/
lib/src.zip
```

**Comment by aahlenst** [comment]
In case of AdoptOpenJDK, it's not a knowledge issue, it's a political one. Do we want to get into that business at all? What's the impact on the ecosystem? I plan to draft a proposal over at https://github.com/adoptopenjdk/tsc, but I didn't get around it.

Our binaries are GPLv2 + Classpath Exception. So nothing stops you there as long as you comply with the license. We're even doing the very same thing for our Docker images with the label `slim`.

**Comment by Jugen** [comment]
An alternative is to use a JRE from [Azul](https://www.azul.com/downloads/zulu-community/?package=jre-fx) instead, that does include JavaFX.

**Comment by aahlenst** [comment]
As of AdoptOpenJDK 14, the deprecated JRE target is effectively broken (see https://github.com/AdoptOpenJDK/openjdk-build/issues/1650). The TSC has decided to introduce a jlinked runtime as JRE replacement for AdoptOpenJDK 11, 14, 15. One objective of that effort is to make it compatible with OpenJFX (not bundle it). 

We'll retain the JRE for 8 and 11.

I close this issue because we won't fix the JRE.
