### ISSUE TITLE
Make interface name standard on all boxes for Atlassian environment

### ISSUE THREAD

**Issue by rdsouza3** [AdoptOpenJDK/openjdk-support#125]
* **Platform and architecture (e.g. Linux/x64**: Windows Server 2016 x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: jdk8u202-b08

* **Variant e.g. HotSpot or OpenJ9**: Don't know

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**:

1. Download the list-interfaces.jar file from https://jira.atlassian.com/browse/CONFSERVER-10979
2. Navigate to jdk8u202-b08\bin 
3. Run java.exe -jar list-interfaces.jar

* **Error messsage and/or description of what is not working as expected**: The ethX value ranges from 0-3, need to configure it so that on all hosts can be eth0

**Comment by aahlenst** [comment]
Thanks for getting in touch. Could you please explain a bit more what the problem is, what you want to achieve and what makes you think that the problem is in AdoptOpenJDK?

**Comment by rdsouza3** [comment]
Hi Andreas, thanks for the quick response!

The issue is when I use the AdoptOpenJDK java.exe -jar list-interfaces command, I want the ethernet adapter to be the same on all 4 nodes in my Confluence cluster. Right now, on two nodes the eth value is eth1 and two of the nodes they are eth0. 

I am trying to automate this so that the value is always eth0 on all 4 boxes. The reason this is an AdoptOpenJDK cause is because this is a Windows box and it doesn't use that value for any of the network adapter names.

**Comment by karianna** [comment]
@rdsouza3 Can you try with jdk8u252 and also one of our adoptopenjdk.net/upstream.html builds.

**Comment by aahlenst** [comment]
Sorry, I might be missing something. I looked into the linked JAR with a decompiler. This is the entire code we're talking about:

```
import java.net.NetworkInterface;
import java.util.ArrayList;
import java.util.Collections;

public class ListInterfaces {
    public ListInterfaces() {
    }

    public static void main(String[] var0) throws Exception {
        ArrayList var1 = Collections.list(NetworkInterface.getNetworkInterfaces());
        System.out.println("interfaces.size() = " + var1.size());

        for(int var2 = 0; var2 < var1.size(); ++var2) {
            NetworkInterface var3 = (NetworkInterface)var1.get(var2);
            System.out.println("networkInterface[" + var2 + "] = " + var3);
            System.out.println("                   (" + var3.getInterfaceAddresses() + ")");
        }

    }
}
```

Java queries the OS and prints what the OS returns. On my system (Linux):

```
interfaces.size() = 4
networkInterface[0] = name:docker0 (docker0)
                   ([/172.17.0.1/16 [/172.17.255.255]])
networkInterface[1] = name:virbr0 (virbr0)
                   ([/192.168.122.1/24 [/192.168.122.255]])
networkInterface[2] = name:enp4s0 (enp4s0)
                   ([/fe80:0:0:0:a14b:8e7d:e366:1311%enp4s0/64 [null], /192.168.178.100/24 [/192.168.178.255]])
networkInterface[3] = name:lo (lo)
                   ([/0:0:0:0:0:0:0:1%lo/128 [null], /127.0.0.1/8 [null]])
```

The relevant implementation code: https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/479d310f10d41ee860e1270a7d4cd5aa56d806a7/src/java.base/windows/native/libnet/NetworkInterface.c#L216. This calls into [GetIfTable](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getiftable) on Windows and assigns names like ethX by enumerating the data returned by  `GetIfTable`. As far as I can see, it makes no guarantees regarding sort order. So it's not a Java problem per-se.

You could try changing the names and see if that changes anything (m comes before v). Otherwise, I'd rely on the adapter name (vmxnet3) instead of the adapter order.
