### ISSUE TITLE
java -version result in segmentation fault while javac -version works

### ISSUE THREAD

**Issue by jbroq** [AdoptOpenJDK/openjdk-support#159]
Hi there,

* Platform: windows 10

* Package
  * OpenJDK8U-jdk_x64_windows_hotspot_8u265b01.msi
  * OpenJDK8U-jdk_x64_windows_openj9_8u265b01_openj9-0.21.0.msi
  * OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10.msi
  * OpenJDK11U-jdk_x64_windows_openj9_11.0.8_10_openj9-0.21.0.zip
  * OpenJDK11U-jdk_x64_windows_hotspot_2020-07-29-05-57.msi
  * OpenJDK11U-jdk_x64_windows_hotspot_2020-07-23-11-55.msi

* Have you tested it with other vendors' java:
it works with jdk.java.net 1.8 hotspot

* no logs in the antivirus software (trend micro) saying that there is an issue with the package.

* git bash
`
java -version`
`
segmentation fault
`
`
javac -version
`
`
javac 11.0.8
`

**Comment by aahlenst** [comment]
Very unlikely to be caused by AdoptOpenJDK. Our builds would not have completed (we run `java -version` as part of the build) and we would have been flooded with support requests. Furthermore, just to be sure, I tested [AdoptOpenJDK 8u265](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_windows_hotspot_8u265b01.msi) on Windows 10 and it worked without a hitch.

Disable every AV except Windows Defender, re-install AdoptOpenJDK and check again.

**Comment by jbroq** [comment]
Thanks I will do that.
Indeed having java -version as part of the build make sens ;)
