### ISSUE TITLE
Openjdk 11.0.8 still fails with "Could not load hsdis-amd64.dll; library not loadable; PrintAssembly is disabled"

### ISSUE THREAD

**Issue by Sbrowneo** [AdoptOpenJDK/openjdk-support#160]
This issue is similar to the one here: https://github.com/AdoptOpenJDK/openjdk-build/issues/893

From my understanding, it said the bug was "Fixed in 11.0.7+4 and better", but here I'm getting the same error message and can't figure out where it's coming from. I apologize if this is the wrong place to post - I'm running pyspark 3.0, but it seems like the bug is happening with the jdk it uses. 

I'm using Openjdk build 11+28, and I also tried with jdk 11.0.8 and got the same error. I wasn't sure what to include in this post, so if more info is needed, please let me know and I will add it accordingly.

Thanks for your help.

![bug](https://user-images.githubusercontent.com/35703276/89332210-9f854980-d658-11ea-9ed7-4b6391a72c47.png)

**Comment by aahlenst** [comment]
11+28 is the reference implementation available from http://jdk.java.net/java-se-ri/11 and almost two years old. You should not use that. It is also visible from the image that it is an Oracle build, not ours.

**Comment by aahlenst** [comment]
@Sbrowneo If it still happens with 11.0.8, please provide instructions how to reproduce the problem.

**Comment by Sbrowneo** [comment]
Correct, it also occurs with 11.0.8 as you can see from this. I will try to create a simple way to reproduce the bug.

![Capture](https://user-images.githubusercontent.com/35703276/89432705-0bbe8680-d707-11ea-8b9a-d6b3b5cd16a1.PNG)

**Comment by aahlenst** [comment]
Could you please share the `hs_err_pid_*.log` that was created?

**Comment by Sbrowneo** [comment]
Sure, here it is
[hs_err_pid7196.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5029841/hs_err_pid7196.log)

**Comment by aahlenst** [comment]
The message about hsdis is a red herring. hsdis is the HotSpot disassembler and part of PrintAssembly. See https://wiki.openjdk.java.net/display/HotSpot/PrintAssembly for more information. It is an optional part of OpenJDK (there seem to be some licensing issues related to binutils). The message merely informs that PrintAssembly is unavailable, not that it is the reason of the crash. The same was already the case in https://github.com/AdoptOpenJDK/openjdk-build/issues/893 you mentioned. Therefore the fix there did not help you because the reason of the crash was different. Which brings us to your problem:

```
org.apache.spark.sql.execution.python.InMemoryRowQueue.add(Lorg/apache/spark/sql/catalyst/expressions/UnsafeRow;)Z (111 bytes) @ 0x000001e93b6add93 [0x000001e93b6ad920+0x0000000000000473]
```

This is the source of your crash according to the crash log. The reason is an access violation. Combined with the widespread use of `sun.misc.Unsafe` in `InMemoryRowQueue`, the problem is very likely a bug Spark that tries to access memory it should not.

Please report the problem to the Apache Spark people.

**Comment by Sbrowneo** [comment]
Understood, thank you for taking the time to help me narrow down the problem!
