### ISSUE TITLE
Java Heap Issues on JDK upgrade

### ISSUE THREAD

**Issue by LamaBimal** [AdoptOpenJDK/openjdk-support#170]
Currently, we have migrated our JDK version from 8.212 to 8.232 in our services. Previously, it is working fine in the older java version. But after upgrading, a heap occurs abruptly on the same hardware configuration. Are there any changes in the memory allocation mechanism between these java versions.

**Comment by aahlenst** [comment]
Release notes are on https://adoptopenjdk.net/release_notes.html.

**Comment by LamaBimal** [comment]
I have looked at changes related to memory level  for the following release notes:
**OpenJDK 8u222 (1.8.0_222-b10)**
S8166684: PPC64: implement intrinsic code with vector instructions for Unsafe.copyMemory()
**OpenJDK 8u252 (1.8.0_252-b09)**
JDK-8238960: linux-i586 builds are inconsistent as the newly build jdk is not able to reserve enough space for object heap
**OpenJDK 8u242 (1.8.0_242-b08)**
S8048556: Unnecessary GCLocker-initiated young GCs

Do these changes are for memory optimizations?. And Is there a memory leak issues in GC in 8.232 version?

**Comment by aahlenst** [comment]
The first one (https://bugs.openjdk.java.net/browse/JDK-8166684) is for PPC64 and a performance improvement. Do you use PPC64?

The second one is a security issue and therefore not public.

The third one is https://bugs.openjdk.java.net/browse/JDK-8048556. Objective was to reduce GC runs.

> a heap occurs abruptly

What do you mean?

I recommend you update to 8u265. Older versions have security problems.

**Comment by LamaBimal** [comment]
I mean to say GC limit exceeded. Mostly Eden space usage is 100%. And service is unresponsive. It occurs frequently after updating the JDK version to 8.232.

**Comment by aahlenst** [comment]
> And service is unresponsive.

This is expected, because the CPU is spending most of the time on GC, otherwise you would not get the exception.

> It occurs frequently after updating the JDK version to 8.232.

It's possible that default settings have changed, especially if you changed the provider of your JVM. There are some -XX options for `java` that should print details. As far as I remember, we haven't come across this problem during testing.

What I would do: Update to the latest version, check/alter the heap size settings, check with JFR/JMC if I can identify what creates excessive garbage. There could be a bug, but that would need a reproducer. If you need help investigating the problem, you can ask on Slack (weekends aren't the best time for that) or ask one of our support providers for help.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
