### ISSUE TITLE
jdk-15+36: macOS: classes.jsa cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by markkolich** [AdoptOpenJDK/openjdk-support#184]
macOS 10.15.6 (19G2021)
[AdoptOpenJDK jdk-15+36](https://adoptopenjdk.net/releases.html?variant=openjdk15&jvmVariant=hotspot)

1. Download the [jdk-15+36 JDK tarball](https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36/OpenJDK15U-jdk_x64_mac_hotspot_15_36.tar.gz)
2. `tar xvf OpenJDK15U-jdk_x64_mac_hotspot_15_36.tar.gz`
3. `sudo mv jdk-15+36 /Library/Java/JavaVirtualMachines`
4. `export JAVA_HOME=$(/usr/libexec/java_home -v 15)`
5. Run `java` or `javac`, see error dialog:

![image](https://user-images.githubusercontent.com/1202420/93688546-79d2c900-fa7b-11ea-8a1e-e1a9e93d2144.png)

I can workaround this by clearing any extended attributes on `Contents/Home/lib/server/classes.jsa`:

```
sudo xattr -c /Library/Java/JavaVirtualMachines/jdk-15+36/Contents/Home/lib/server/classes.jsa
```

Should I have to do that?

**Comment by aahlenst** [comment]
This is expected behavior if you download the tarball through Safari or another software that adds the quarantine attribute to the downloaded tarball. Tarballs aren't notarized. Remove the attribute or use curl/wget.

Please see the section on hardened runtime support in https://blog.adoptopenjdk.net/2020/04/adoptopenjdk-8u252-1107-and-1401-available/ for details.
