### ISSUE TITLE
Incorporate Eclipse SWT into OpenJDK distribution

### ISSUE THREAD

**Issue by JayJay3** [AdoptOpenJDK/openjdk-support#189]
Now OpenJDK is in Eclipse foundation. I think it will be great if OpenJDK distribution include SWT jar file. Dealing with SWT is very inconvenient. Inclusion will make Java applications much simpler!

**Comment by aahlenst** [comment]
> Now OpenJDK is in Eclipse foundation.

OpenJDK is still a standalone project. AdoptOpenJDK plans to move, but that has not happened yet. Whether AdoptOpenJDK is a member of the Eclipse Foundation or not is unrelated to your request.

> I think it will be great if OpenJDK distribution include SWT jar file. Dealing with SWT is very inconvenient. Inclusion will make Java applications much simpler!

We're not in a position to make this happen. It would only further fragment the ecosystem because we cannot force other distributors to follow our example. AdoptOpenJDK would have it, but Oracle JDK, Azul Zulu, ... would not. Furthermore, it would fly in the face of all efforts to unbundle OpenJDK and make it more modular like it has been done with OpenJFX. When you use OpenJFX, you as application developer create targeted runtimes that include the necessary JARs and deliver those together with your app. The necessary tools are shipped with any newer JDK: jlink and jpackage. Talk to the SWT people if you think they could improve the development experience in that area.
