### ISSUE TITLE
Using system-wide 125% scaling makes java applications bloated.

### ISSUE THREAD

**Issue by JeljoGb** [AdoptOpenJDK/openjdk-support#20]
**Platform:** Windows 10

**Architecture:** x64

I set my windows dpi on the (recommended) 125%, since i have a 15" laptop with 1920:1080 resolution. Everything is tiny if I don't do this.
https://i.imgur.com/qLBYCcM.png

If I open the prepackaged runelite.exe (a client for a game written in java), which has java included, without touching the dpi settings, it blows it up to 125%, which is what should happen, but not what I want.
If I select the bottom checkmark, and set it to "application", it goes back to regular crisp 100%.
https://i.imgur.com/a3gDszE.png

But if I use the runelite.jar file, and it uses my computer's java installation, which is currently AdoptOpenJdk 13, I can't have it go to 100%. It's always 125%.
Highdpi setting changed runelite.exe in front, highdpi settings for "java.exe" and "javaw.exe" changed runelite.jar in the back: https://i.imgur.com/V9nzXm.png
Compatibility settings on both are the same.
I can change the size of the .jar one, but that just crops the client: https://i.imgur.com/n6mBol.png

This happens with every .jar file. I'm at my wit's end.

Another piece of information is that it used to work with an earlier version of java. (Might be java 8)
But newer applications required at least java 11, and that's where I am now.

**Comment by tresf** [comment]
> @JeljoGb Have you tried with the adoptopenjdk.net/upstream.html build?

His bug report is against AdoptOpenJDK13.  The link provided is only for AdoptOpenJDK8 and AdoptOpenJDK11.

> Could you explain to me how I should install that?
> I tried opening the .jar with the javaw.exe in that package, but that did nothing.
> Do I have to put the files somewhere specific?

I've prepared a basic video explaining how to run Java from a zip file.  It requires opening up a Command Prompt window and dragging the `java.exe` (or alternately `javaw.exe`) into that Window.  Hopefully it helps.

> But if I use the runelite.jar file, and it uses my computer's java installation, which is currently AdoptOpenJdk 13, I can't have it go to 100%. It's always 125%.

Have you reached out to the runelite community yet?  They may already be aware of this issue and have recommendations https://github.com/runelite/runelite/issues/7638.  It's often advantageous to keep the developers involved so that any recommendations or code workarounds that are provided here can be vetted by someone familiar with development and troubleshooting Java applications.  In most cases, projects like runelite will have a bug marked as "upstream" to indicate that the bug exists but there's no solution has been provided by the upstream developers (in this case Java) yet.

Anyway, I use AdoptOpenJDK11 with HiDPI and it works pretty well, so I also wonder if this problem is isolated to AdoptOpenJDK13.  I have a HiDPI (400%) monitor to test on so I can probably help identify the scope of the issue.

**Comment by tresf** [comment]
Forgot the video link.  Here it is: https://youtu.be/K0Rwtm9P-DQ

**Comment by tresf** [comment]
Here's `RuneLite.jar` running in a Windows 10 VM at 300% scale factor.  I can test on physical hardware next, but at a glance, they all look the same.

![image](https://user-images.githubusercontent.com/6345473/72017663-1ded4a80-3234-11ea-8bdf-604c9049ce89.png)

**Comment by tresf** [comment]
@karianna based on the OPs description, it sounds like newer versions of Java are properly honoring the Windows fractional screen scaling, which is correct and by design.

I believe the OP is asking for a technique to disable fractional screen scaling, which mimics versions of Java that were not properly scaling the interface.

It appears that the old behavior can be forced using a technique described here: https://github.com/kirill-grouchnikov/substance/issues/48#issuecomment-337963498

```
java –Dsun.java2d.uiScale=1.0 -jar RuneLite.jar
```

Unfortunately, this doesn't work.  It initially launched without scaling, but then `RuneLite.jar` uses its own stub launcher which overrides command-line parameters.

This normally, you need to use an environmental variable to set this permanently, but I can't get that to work either.

@JeljoGb I strongly feel this needs to be asked over at the RuneLite repository.  Ask them how you can provide the parameter `–Dsun.java2d.uiScale=1.0` to RuneLite to disable fractional scaling on your computer.

Note, fractional scaling is not supported by Linux or macOS, so this is a very specific request that has to do with RuneLite and Windows.  For some reason Windows laptops shipped with odd screen sizes that required 125% scaling, resulting in the exact blurriness you're describing.  This isn't a Java bug specifically, but rather a nuance with the app you're trying to use.

**Comment by JeljoGb** [comment]
Wow, thank you very much for this extensive reply!

I'll send this thread to the developers at RuneLite.

**Comment by JeljoGb** [comment]
I have tried most of the things you've written here, java –Dsun.java2d.uiScale=1.0 -jar RuneLite.jar
 for example briefly works, but then it overrides as you said.

They've told me 
![image](https://user-images.githubusercontent.com/34870401/72093338-78f66e80-3314-11ea-8bbb-9140d90b4911.png)
The easiest solution would seem to be to allow for arguments to be passed to the jar, so I'll push on that.

I sent Windows a feedback thing to let me selectively disable scaling instead of letting it be done by the app.

**Comment by JeljoGb** [comment]
They have explained to me that it is currently impossible to pass arguments to their launcher, but I did find this: https://github.com/runelite/launcher/pull/19, so I'm pushing on that now.

Thanks for all your help!

**Comment by JeljoGb** [comment]
Even newer update!
There is a way to pass arguments to the client, and that's what I'm using now.

Thank you for all your help, and sorry for blaming it on java.
