### ISSUE TITLE
TLS 1.3 handshake server name indication is missing on a session resume (JDK-8211806)

### ISSUE THREAD

**Issue by morvael** [AdoptOpenJDK/openjdk-support#232]
Please merge the fix for this bug:
https://bugs.openjdk.java.net/browse/JDK-8211806
into AdoptOpenJDK11 LTS.

**Comment by morvael** [comment]
I wonder why isn't this already fixed, since it was backported to OpenJDK 11.0.2, and AdoptOpenJDK is now on 11.0.9. You're not merging http://hg.openjdk.java.net/jdk-updates/jdk11u/ ?

**Comment by morvael** [comment]
What's funny is that https://bugs.openjdk.java.net/browse/JDK-8212885 removed the fix for JDK-8211806, yet I still have the issue with the server_name extension going AWOL.

**Comment by aahlenst** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/6dd341a4aba2dfd023947dade8534325f019883f#diff-40689ae0fa56a251a0ccf9b3ba92375b8079d9bb1d2f7ae8a7a1b615a666b9d2 is the fix. There's a regression test included: ResumeTLS13withSNI. Because it's still included and I haven't seen it in the problem list, it's rather safe to assume that the exact problem did not reappear. So it might make sense to run it yourself and see whether you're problem actually is the same or not (writing a test yourself is a great start).

**Comment by morvael** [comment]
The problem happens when running on WildFly, on the same machine and JDK in a regular Java app, the server_name extension is retained. So maybe it's not that issue in AdoptOpenJDK or JDK in general, but in WildFly. Sorry, I'm confused why this happens.
