### ISSUE TITLE
Cacerts lost during upgrade

### ISSUE THREAD

**Issue by pinelgr** [AdoptOpenJDK/openjdk-support#236]
Hello,

I have installed the 8u265 version with msiexec /i file.msi /qb
I put our certificats with keytool command.
So, the C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\cacerts has well been modified

And when I install the new version 8u275 with the same command, a new directory C:\Program Files\AdoptOpenJDK\jdk-8.0.275.01-hotspot is created, the old directory is deleted and the cacerts lost.

We have an Ivanti process whose purpose is to make automatic upgrades without the possibility of putting options in the command, and unfortunately the cacert is not postponed and the JAVA_HOME is not updated.

What solution would we have
Thank you very much

**Comment by aahlenst** [comment]
I know that it is very popular to modify cacerts for some reason. I think it's wrong. Although cacerts doesn't change frequently, it does change. New root CA certificates are added, outdated removed and insecure certificates marked as insecure. So not updating cacerts when a new version comes out isn't a good idea. Theoretically, an installer could patch the existing cacerts file, but the necessary tooling does not exist. It would also require changes to the MSIs which might cause trouble. And cacerts would need to be relocated to the user profile so that each user gets its own certificates.

There are several approaches you can take:

* Pass the necessary arguments to java to use a custom trust store. https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#Customization lists the properties you can modify.
* Relocate the standard cacerts using an NTFS junction (save the trust store in `C:\something\cacerts` and let the cacerts in `C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\cacerts` point there by replacing the file after the MSI did its job).
* Use the [SunMSCAPI](https://docs.oracle.com/en/java/javase/14/security/oracle-providers.html#GUID-4F1737D6-1569-4340-B140-678C70E63CD5) security provider. Instead of using cacerts as trust store, it uses the Windows certificate store. So by installing the custom certificates into the Windows certificate store, java will automatically pick it up. https://stackoverflow.com/a/49011158/759042 describes various ways to active the SunMSCAPI security provider.

I think the last option is the best because you just have to maintain one set of certificates in one place. But your mileage may vary. If you're successful with one of these options, please let us know.

**Comment by pinelgr** [comment]
We have auto-signed certificates, that’s why we usually put them on the cacerts
We’re going to look at the approaches you’re giving.
However, we don’t necessarily have control over how applications installed on windows servers launch Java or the way each application searches for, and validates certificates.
Another question: Our automatic upgrade process Ivanti (https://www.ivanti.fr/) upgrades AdoptOpenJDK in installing the msi without parameter, so by default with INSTALLLEVEL=1, and JAVA_HOME doesn't updated
Is it possible to put the FeatureJavaHome in INSTALLLEVEL 1?
Thank you very much.

**Comment by aahlenst** [comment]
> However, we don’t necessarily have control over how applications installed on windows servers launch Java or the way each application searches for, and validates certificates.

That's why nowadays it's recommended to bundle Java with your application. The tools jlink and jpackage have been introduced to make this easier.

> Another question: Our automatic upgrade process Ivanti (https://www.ivanti.fr/) upgrades AdoptOpenJDK in installing the msi without parameter, so by default with INSTALLLEVEL=1, and JAVA_HOME doesn't updated
Is it possible to put the FeatureJavaHome in INSTALLLEVEL 1?

Well, level 1 would then more or less become level 2. And it would be a breaking change. I'd rather ask the Ivanti people to allow supplying arguments. That's more future-proof.

**Comment by ChristianStadelmann** [comment]
@aahlenst wrote:
> I know that it is very popular to modify cacerts for some reason. I think it's wrong.

I *think* so too, but sadly some companies are using man-in-the-middle proxies¹ which bring their own certificates. To make any java runtime work in setups like this, it needs to support installing custom certificates into the JRE. Integrating the certificates into applications is no option either because users may also want to use publicly available software like the eclipse IDE within the company network.

¹ for "security" or at least something which is sold as "security".

**Comment by aahlenst** [comment]
> This does also affect the JRE.

Sure. It's basically the same thing, just without javac and jmods. And the JRE is also deprecated and already broken in >= 14.

> To make any java runtime work in setups like this, it needs to support installing custom certificates into the JRE.

In https://github.com/AdoptOpenJDK/openjdk-support/issues/236#issuecomment-758228030 I gave two options that do not require changes to the built-in trust store. So on Windows and macOS, you can delegate to the OS's trust store and you should really do it, no matter whether you actually need custom certificates or not.

On Linux, only the symlink approach (NTFS junction on Windows) works because there's no standardized API to query the system's trust store. The Linux packages shipped with Debian, CentOS, etc. already work like that. We're a bit behind here but it's coming soon-ish.

> Integrating the certificates into applications is no option either because users may also want to use publicly available software like the eclipse IDE within the company network.

In the "future" (a.k.a. JDK >= 11), the Java runtime is supposed to be built into and shipped with applications like the Eclipse IDE.

**Comment by ChristianStadelmann** [comment]
@aahlenst:
Thanks for the hints!

In case someone tries to use the system certificate path in eclipse, [here is how you do it](https://stackoverflow.com/a/65794452/12932497).

**Comment by aahlenst** [comment]
Considering the lack of activity in the recent weeks, it looks like the question is answered.
