### ISSUE TITLE
When should I expect the Java 11.0.10 release to be available?

### ISSUE THREAD

**Issue by JasonMathison** [AdoptOpenJDK/openjdk-support#242]
This is my first time waiting on a release to be available.  The Mozilla based Trusted Root Certificate List in 11.0.10 solves a problem in one of my projects!  The support page says that 11.0.10 should have been released yesterday.  Should I expect a couple of day lag for the release to be cut, or is there a conversation I can watch somewhere about the status of this release?

Sorry if I am being impatient or this is the wrong forum to ask this.  I really appreciate the effort that goes into keeping Java up-to-date and freely available!
--Jason

**Comment by aahlenst** [comment]
As it says on our front page: 

> 20th January 2021 AdoptOpenJDK 8u282, 11.0.10, and 15.0.2 binaries will be released in 24-72 hours!

Docker containers, Linux packages can take a few days extra. The pipelines are currently running.

**Comment by JasonMathison** [comment]
I have been refreshing the blog and the the releases page and my eyes just rolled right over that.  Sorry and thanks again for making this project happen.

**Comment by aahlenst** [comment]
For the future: OpenJDK makes their planned releases on the Tuesday that's closest to the 17th of January, March, April, July, September, and October. That's the date you find on our support page. For some platforms, the source release comes even later. We cannot really start building and running the test suites before OpenJDK releases the source code. So that's why we're always later. Rule of thumb: Expect the first batch of binaries by Thursday.

**Comment by aahlenst** [comment]
Released: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.10%2B9

Might take a while for the website to pick it up.
