### ISSUE TITLE
OpenJ9 jdk8u282-b08 fails to start on MacOS

### ISSUE THREAD

**Issue by Micu76** [AdoptOpenJDK/openjdk-support#250]
Hi.
I am bundling the OpenJ9 version of the AdoptOpenJDK JRE "8u282-b08" in my application's installer built through "install4j".
My application works fine on Windows, however the Mac version of the launcher of my Java application fails with the following error on MacOS:

`JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata. 200M requested`

The issue I am experimenting seems to be exactly the same as reported here:

https://github.com/eclipse/openj9/issues/10416

This issue report describes a linking option which shall be specified in order to fix this JVM initialization error. Is this linking option something which should be specified by the AdoptOpenJDK team while building the OpenJ9 version of the JRE binaries?

Any comment would be greatly appreciated.
Regards,

Marco

**Comment by pshipton** [comment]
The required option is built in to Adopt builds. I expect the Adopt builds are using it, otherwise all the release testing would have failed.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/make/closed/autoconf/custom-spec.gmk.in#L105

Does the application installer create a custom launcher where the required option is not specified? Ideally you should specify the required linker option when creating the launcher, if install4j allows that.

One way to work around the problem is to use the Large Heap build, which doesn't require the special option, although it will use more memory to run.

**Comment by ingokegel** [comment]
install4j 8.0.11 will fix this issue
