### ISSUE TITLE
Crashes my mac

### ISSUE THREAD

**Issue by GeorgeKosrs** [AdoptOpenJDK/openjdk-support#284]
Can you please help me? when I enable the gpu plugin It crashes my mac after a few hours

here are my logs

[jvm_crash_pid_7039.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208594/jvm_crash_pid_7039.log)
[jvm_crash_pid_30251.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208595/jvm_crash_pid_30251.log)
[jvm_crash_pid_56604.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208596/jvm_crash_pid_56604.log)
[jvm_crash_pid_71781.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208597/jvm_crash_pid_71781.log)
[jvm_crash_pid_99320.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208598/jvm_crash_pid_99320.log)
[jvm_crash_pid_7992.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6208600/jvm_crash_pid_7992.log)

**Comment by aahlenst** [comment]
So, you're having problems with runelite. Looks like we cannot help you because the crashes happen outside the JVM. runelite crashes inside the driver of the graphics card (AMDRadeonX6000GLDriver) and that's so deep inside native code that there isn't even a trace of the JVM inside the stacktrace. Best you can do is update your Mac (if you haven't already) and then report the problem to runelite.

**Comment by GeorgeKosrs** [comment]
> So, you're having problems with runelite. Looks like we cannot help you because the crashes happen outside the JVM. runelite crashes inside the driver of the graphics card (AMDRadeonX6000GLDriver) and that's so deep inside native code that there isn't even a trace of the JVM inside the stacktrace. Best you can do is update your Mac (if you haven't already) and then report the problem to runelite.

Thank you. Sorry for bothering you and contacting the wrong person. Have a good day!
