### ISSUE TITLE
Eclipse IDE Won't Start With jdk-11.0.6+10 on macOS

### ISSUE THREAD

**Issue by gopackgo90** [AdoptOpenJDK/openjdk-support#52]
* **Platform and architecture (e.g. Linux/x64**:
macOS Catalina 10.15.3/x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
No

* **Steps to reproduce**:
1. Install Eclipse IDE, https://www.eclipse.org/downloads/
2. Try to start Eclipse

* **Error message and/or description of what is not working as expected**:
Trying to start the Eclipse.app results in the following error:
>Alert
>
>Failed to create the Java Virtual Machine.

Executing Eclipse from the Terminal results in:
>% /Applications/Eclipse.app/Contents/MacOS/eclipse                      
>Error: could not find libjava.dylib
>Failed to GetJREPath()

Eclipse starts fine using JDK:
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

**Comment by aahlenst** [comment]
Looks similar to other reports we got, e.g. [this one on Slack](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1580745173109900). Apple's notarization requirement forced changes to the OpenJDK file organization on disk, see https://hg.openjdk.java.net/jdk/jdk/rev/7a1e6bd6a836. 11.0.6 is the first release with the change. This seems to break Eclipse. Upstream bug is at https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482.

**Comment by karianna** [comment]
The upstream fix has landed, we'll see this in 11.0.7

**Comment by aahlenst** [comment]
14+36 seems to have the problem. As I read the entries in JBS, the fix will be in 14.0.2.

**Comment by aahlenst** [comment]
The official stance of AdoptOpenJDK (and, as I heard, OpenJDK itself) is that this has to be addressed by Eclipse. `libjava.dylib`, which previously was a symlink, is now a hard copy and will remain a hard copy because Apple won't allow any symlinks for notarized binaries. And because it  is crucial that `libjava.dylib` is in the place it currently is, we won't move it, either.

**Comment by kjjaeger** [comment]
So Apple now disallows all symlinks in a program?  I just downloaded Azul's Zulu 14 and it is still using the symlink MacOS/libjli.dylib -> ../Home/./lib/libjli.dylib.  Does that mean Azul's binaries are not notarized?

**Comment by aahlenst** [comment]
As far as I know, there are different requirements depending on whether you want to notarize something just for running it or for bundling it. That might explain the difference. We strive to offer full bundle support. I am no expert regarding notarization, though. Maybe @gdams can chime in who has the lead in this area.

**Comment by gdams** [comment]
@kjjaeger as far as I can tell Azul currently does not notarize their zulu binaries and therefore have not hit the same symlink issue that both we and Oracle have had to resolve.

**Comment by PerMildner** [comment]
@aahlenst The [OpenJDK bug](https://bugs.openjdk.java.net/browse/JDK-8238225) seems to be resolved with a fix to the OpenJDK file  `src/java.base/macosx/native/libjli/java_md_macosx.m`, i.e. it does not look as if OpenJDK thinks "that this has to be addressed by Eclipse" (and given that the fix is in OpenJDK itself, it is not clear whether this _can_ be addressed in the Eclipse launcher).

(but I may be completely wrong, I am not involved in OpenJDK or Eclipse development)

**Comment by aahlenst** [comment]
@PerMildner I relayed what I was told. 

Personal addendum: I agree with your interpretation of the JBS entry. I interpreted it the same way as you do before. On the other hand: Apple's requirements aren't fully documented and things have been in flux until recently (and maybe still are). So the symlink thingy might break in the future. Furthermore, I see no reason why Eclipse wants it to be symlink.

**Comment by ccleve** [comment]
How is this closed? 11.0.7 isn't released yet, homebrew doesn't allow you to downgrade to 11.0.5, some people may not be able to upgrade to 11.0.7 when it comes out, and we're totally dead in the water. I'm aware of no workarounds.

**Comment by aahlenst** [comment]
@ccleve AdoptOpenJDK is not the right place to look for a fix. This has either to be fixed by Eclipse or OpenJDK itself. In my opinion, it's up to Eclipse. Knock at their door and ask for a fix or at least an explanation why this should be a symlink. I haven't seen one. Even if OpenJDK reverts to symlinking `libjava.dylib`, it's very likely that we end up in the same situation, soon. Apple strives to get rid of symlinks in notarized application bundles. And Apples crusade for notarization and hardened runtime support is what brought us here, anyway. 

I do not follow the reasoning of not being able to upgrade to 11.0.7. If you cannot update from 11.0.6 to 11.0.7, it's unlikely you can update from 11.0.6 to a patched 11.0.6. 11.0.7 contains only bugfixes and security fixes. It's not like back in the day with 7u and early 8u when we got changes that were like going from 9 to 10.

There's a workaround: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482#c11

**Comment by PerMildner** [comment]
@aahlenst It is not Eclipse that wants a symlink. As is clear from the OpenJDK fix for this bug, the problem is that some code in OpenJDK wants this to be a symlink. See my [comment above](https://github.com/AdoptOpenJDK/openjdk-support/issues/52#issuecomment-603742078). It is not clear that Eclipse _can_ work around this OpenJDK-bug.

**Comment by aahlenst** [comment]
@PerMildner My bad. Another reason why OpenJDK and Eclipse have to work this out.

It's less than two weeks until the next CPU. Time to grab one of our nightly builds and check whether they work.
