### ISSUE TITLE
java.lang.Runtime.availableProcessors() method returning incorrect result on computers with multiple CPU sockets

### ISSUE THREAD

**Issue by pDarbhamulla** [AdoptOpenJDK/openjdk-support#60]
* **Platform and architecture (e.g. Linux/x64**:

	Instance Type: Amazon c5.24xlarge
	Number of vCPUs: 96
	Sockets: 2

	Windows Server 2019 Datacenter
	Processor: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz (2 processors)
	System type: 64-bit Operating System , x64-based processor

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
	openjdk 11.0.4 2019-07-16
	OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
	OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**:

* **Have you tested it with other vendors' java**:
	No

* **Steps to reproduce**:
	Execute - Runtime.getRuntime().availableProcessors()

	public class TestGetAvailableProcessors {
		public static void main(String[] args) {
			System.out.println(Runtime.getRuntime().availableProcessors());
		}
	}

* **Error messsage and/or description of what is not working as expected**:

	Actual Result:
		Runtime.getRuntime().availableProcessors() returns 48
	 
	Expected Result:
		As there are two sockets on this VM with 48 processors each, expecting Runtime.getRuntime().availableProcessors() to return 96 instead of 48
		
	What is not working as expected:
		Results pertaining to only one socket are returned instead of all sockets.

Kindly let me know if I can provide any additional details.

**Comment by karianna** [comment]
@pDarbhamulla Can you try with 11.0.6?

**Comment by pDarbhamulla** [comment]
@karianna 

Thanks for looking into this. I tried on 11.06, still getting the same result - only one CPU socket is used.

openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

**Comment by aahlenst** [comment]
I cannot reproduce the behaviour on a bare metal machine. 

```
PS C:\Users\Administrator> wmic cpu get NumberOfLogicalProcessors
NumberOfLogicalProcessors
12
12
```

AdoptOpenJDK with the test program mentioned above reports 24 available processors which is the expected answer.

Please check if the number Windows reports is different than the number that AdoptOpenJDK reports.

**Comment by grzesuav** [comment]
@pDarbhamulla @aahlenst I doubt this is adopopenjdk bug, we do not change source code of openjdk.

Things to check :
* how java get's number of processors on windows
* check how many processors used method returns when invoked (for example from C++ code)

as an workaround you might try to use (https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE) explicitly set this number (via `-XX:ActiveProcessorCount=xx`)

**Comment by grzesuav** [comment]
if there is indeed error how java gets this number, I would suggest to report it on. To confirm that, would be useful to test using other vendor.

Would also point to https://bugs.openjdk.java.net/browse/JDK-5048379 .

**Comment by pDarbhamulla** [comment]
> wmic cpu get NumberOfLogicalProcessors

@aahlenst 

I ran wmic command and Windows reports the correct number of available processors and this is different than the number that AdoptOpenJDK reports

![image](https://user-images.githubusercontent.com/20075884/75510628-77eece80-59a0-11ea-8929-b1ce0f4b933c.png)

**Comment by aahlenst** [comment]
I launched one of these instances myself. The Red Hat build of 11.0.6 as well as JDK 14 EA build 36 show the same problem.

I guess this one should be reported to the OpenJDK project.

**Comment by jerboaa** [comment]
This is the impl of `os::active_processor_count()` on windows:
http://hg.openjdk.java.net/jdk-updates/jdk11u/file/f7b46111931c/src/hotspot/os/windows/os_windows.cpp#l761

`processor_count()` is set here:
http://hg.openjdk.java.net/jdk-updates/jdk11u/file/f7b46111931c/src/hotspot/os/windows/os_windows.cpp#l3727

If you think there is a bug in this impl, I'd be happy to report it upstream.

**Comment by aahlenst** [comment]
I did some more digging...

The [c5.24xlarge](https://aws.amazon.com/de/ec2/instance-types/c5/) has 96 vCPUs. The CPU is a [Intel Xeon 8275CL](http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%208275CL.html) (didn't found the specs on the Intel website) which has 24 cores and can do 48 threads. Two of those are in a c5.24xlarge which makes 48 cores and 96 threads.

OpenJDK uses [GetSystemInfo()](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsysteminfo) to query the number of available processors, which returns [SYSTEM_INFO](https://docs.microsoft.com/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info). It uses the field `dwNumberOfProcessors` of the `SYSTEM_INFO` struct. According to the linked Microsoft docs, this is:

> The number of logical processors in the current group.

What processor groups are is explained on https://docs.microsoft.com/windows/win32/procthread/processor-groups:

> Support for systems that have more than 64 logical processors is based on the concept of a processor group, which is a static set of up to 64 logical processors that is treated as a single scheduling entity. Processor groups are numbered starting with 0. Systems with fewer than 64 logical processors always have a single group, Group 0.

This means, with 96 logical processors there must be at least two groups. This indicates that `dwNumberOfProcessors` is insufficient because it only returns the number of logical processors in the **current** group.

But there's more, again quoting https://docs.microsoft.com/windows/win32/procthread/processor-groups:

> By default, an application is constrained to a single group, which should provide ample processing capability for the typical application. The operating system initially assigns each process to a single group in a round-robin manner across the groups in the system. A process begins its execution assigned to one group. The first thread of a process initially runs in the group to which the process is assigned. Each newly created thread is assigned to the same group as the thread that created it.

So if the JVM is constrained to a single group, 48 is the right answer. The remaining question to be answered: Does OpenJDK support multiple processor groups? JBS has the answer in [Hotspot should be able to use more than 64 logical processors on Windows](https://bugs.openjdk.java.net/browse/JDK-6942632): No, and it won't be added. The right approach is to use multiple JVMs on big hardware.

Conclusion: Works as designed.

**Comment by karianna** [comment]
For the curious - my OpenJDK group at Microsoft is looking to work with the Windows team to potentially change this.  But these sorts of things take a long timeframe.
