### ISSUE TITLE
Request port of JDK-8201429 to AIX Java 8

### ISSUE THREAD

**Issue by JerryBoldt** [AdoptOpenJDK/openjdk-support#73]
* **Platform and architecture (e.g. Linux/x64**: 
Japanese AIX 7.1/ppc64 TL5 or AIX 7.2/ppc64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
 1.8.0_232 and 1.8.0_242

* **Variant e.g. HotSpot or OpenJ9**: 
OpenJ9 

* **Have you tested it with other vendors' java**: 
works with IBM Java 1.8 

* **Steps to reproduce**: 
1. Using an AIX 7.1 TL4 OS on Japanese
2. Install Java from OpenJDK 
3. Run the sample code which create a JTextField object
4. Try to edit some text in the text field control
* **Error message and/or description of what is not working as expected**: 
Unable to edit in Text fields, in the terminal there is a Japanese message which translation is “invalid input type”

The error we are reporting is also found here: JDK-8201429
It is a known bug, only resolved in Java 11.  We request this also be fixed in Java 8.  We have a planned National Language release for one product very soon, and request a fix in 3 weeks. We will also have a second product impacted in a few months.

Here is the sample code to replicate this:

public class Test {
    public static void main(String s[])
    {                      
        // create a new frame to store text field
        JFrame frame = new JFrame("IME Bug");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        // create a JTextField 
        JTextField tf = new JTextField(); 
        tf.setPreferredSize(new Dimension(100, 30));
  
        // create a panel to add textfield 
        JPanel p = new JPanel();
        p.add(tf); 
        
        // add panel to frame 
        frame.add(p); 
  
        // set the size of frame 
        frame.setSize(300, 300); 
  
        frame.setVisible(true);
    }
}

**Comment by aahlenst** [comment]
If you want a backport to OpenJDK 8, it might be best to try to persuade someone on our [Slack channel](https://adoptopenjdk.net/slack.html) with [JBS access](https://bugs.openjdk.java.net/secure/Dashboard.jspa) to file that request on your behalf. We do not apply patches on top of OpenJDK.

The next CPU is not due until 2nd half of April which might be too late for you. And even if it is not, it might take longer to arrange a backport. Maybe [one of the companies providing support for AdoptOpenJDK](https://adoptopenjdk.net/support.html#commercial-support) can help.

**Comment by JerryBoldt** [comment]
Andreas, I am new to Slack.  How does one do what you are suggesting?

**Comment by aahlenst** [comment]
@JerryBoldt You did everything as I would have done it. People from Europe have already left for the weekend, so some patience might be necessary.

**Comment by karianna** [comment]
I've pinged the jbs channel on slack.

**Comment by JerryBoldt** [comment]
Thank you

**Comment by aahlenst** [comment]
@jerboaa Do you need more info to initiate a backport of JDK-8201429 to JDK 8?

**Comment by jerboaa** [comment]
@aahlenst Thanks. I don't need more info for this.

There seems to be a misconception of how backports to jdk 8u work. Unfortunately, it's not like a JDK 8u backport gets requested and somebody magically does the work for you. That's not how it works. It's a community project. It's best for the community to do the backport, come up with a patch, then I or some other OpenJDK contributor can work with them to get the patch upstream. With that said, the proposed bug, JDK-8201429, is rather large and seems to be quite risky for a stable 8u release. It should be considered to move to a newer JDK rather than relying on maintenance releases to get major changes. If you really need this in OpenJDK 8u upstream, steps would be to:

1. Contribute a patch (be sure contributor is an OCA signatory)
2. Thoroughly test the proposed patch. Ensure it doesn't regress the JDK elsewhere.
3. Raise the patch for backport review on the [upstream mailing list](http://mail.openjdk.java.net/pipermail/jdk8u-dev/)
4. Once an JDK 8u reviewer approved the patch, propose it for approval to the maintainers (`jdk8u-fix-request` label with "Fix Request" comment in JBS)

For 2 and 4 you might need OpenJDK project authors to help you (host the patch on cr.openjdk.java.net and add tags to the bug system).

More info here:
https://wiki.openjdk.java.net/display/JDKUpdates/How+to+contribute+a+fix
https://wiki.openjdk.java.net/display/jdk8u

**Comment by aahlenst** [comment]
@jerboaa Thanks for the detailed explanation :)

@JerryBoldt To sum up, we as AdoptOpenJDK cannot help you here. Please either follow Severin's advice or, alternatively, [reach out to one of the companies providing support for AdoptOpenJDK](https://adoptopenjdk.net/support.html#commercial-support).

I close the issue because there isn't anything left to do here.
